name: computer_shop_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.5
  shared_preferences: ^2.2.2
  auto_size_text: ^3.0.0
  flutter_screen_lock: ^9.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  formz: ^0.6.1
  dartz: ^0.10.1
  dio: ^5.3.4
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  retrofit: ^4.0.3
  injectable: ^2.3.2
  package_info_plus: ^4.2.0
  bloc: ^8.1.2
  permission_handler: ^11.0.1
  flutter_vlc_player: ^7.4.0
  slidable_button: ^3.0.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  gap: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/images/

  fonts:
    - family: DBHelvethaica
      fonts:
        - asset: assets/fonts/DB-Helvethaica-X-v3-2.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ComShop1.png"
